
services:
  db:
    image: postgres:18.1
    shm_size: 128mb
    ports:
      - "127.0.0.1:10012:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: Secretcom123
      POSTGRES_DB: golang_starter
    volumes:
      - dev_golangstarter_db:/var/lib/postgresql/18/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5

  mailhog:
    image: mailhog/mailhog:v1.0.1
    ports:
      - "127.0.0.1:1025:1025"  # SMTP
      - "127.0.0.1:8025:8025"  # Web UI

  adminer:
    image: adminer
    ports:
      - "10013:8080"
    environment:
      ADMINER_DEFAULT_SERVER: db
      ADMINER_DEFAULT_PORT: "5432"
    depends_on:
      - db

volumes:
  dev_golangstarter_db:
